version: "3.0"
services: 
    client:
        container_name: client_container
        ports:
            - "80:80"
        restart: always
        build: ./client
        depends_on: 
            - server

    server:
        container_name: server_container
        ports:
            - "5000:5000"
        restart: always
        build: ./server